# Generated by Django 3.2.7 on 2022-12-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_ad_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='benefits',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
