# Generated by Django 3.2.7 on 2022-12-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_ad_benefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='positions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='positions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
