# Generated by Django 3.2.7 on 2022-12-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20221221_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'get_latest_by': 'last_updated', 'ordering': ('last_updated',)},
        ),
        migrations.AddField(
            model_name='resume',
            name='documents',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
