# Generated by Django 3.2.7 on 2022-12-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20221223_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='statistics',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
