# Generated by Django 3.2.7 on 2022-12-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_ad_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DELETED', 'Deleted'), ('SOLD', 'Sold'), ('REVIEW', 'Review'), ('UNPUBLISHED', 'Unpublished')], default='ACTIVE', max_length=25),
        ),
    ]
